..........E...EE........................E..F...........
======================================================================
ERROR: Tests that a user's prompt list displays public prompts and only that user's private prompts
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/laura/tod/../tod/prompt/tests.py", line 119, in test_promptOwnerFilter
    prompts = response.context.get('prompts')
AttributeError: 'list' object has no attribute 'get'

======================================================================
ERROR: Tests that rounds selected equals rounds created with sufficient prompts
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/laura/tod/../tod/game/tests.py", line 215, in test_excessPrompts
    self.game.create_game(rounds_selected = 5)
  File "/home/laura/tod/../tod/game/models.py", line 83, in create_game
    prompt_count = prompts[current_difficulty].count()
AttributeError: 'Prompt' object has no attribute 'count'

======================================================================
ERROR: Tests that rounds selected equals maximum rounds available with insufficient prompts
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/laura/tod/../tod/game/tests.py", line 227, in test_insufficientPrompts
    self.game.create_game(rounds_selected = 5)
  File "/home/laura/tod/../tod/game/models.py", line 83, in create_game
    prompt_count = prompts[current_difficulty].count()
AttributeError: 'Prompt' object has no attribute 'count'

======================================================================
ERROR: Tests that the game's absolute url redirects to the right pages
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/laura/tod/../tod/game/tests.py", line 455, in test_redirects
    self.assertRedirects(response, 'game/2/select_prompts/', status_code=302, target_status_code=200)
  File "/usr/lib/python2.5/site-packages/django/test/testcases.py", line 98, in assertRedirects
    redirect_response = response.client.get(path, QueryDict(query))
  File "/usr/lib/python2.5/site-packages/django/test/client.py", line 219, in get
    return self.request(**r)
  File "/usr/lib/python2.5/site-packages/django/core/handlers/base.py", line 82, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.5/site-packages/django/contrib/auth/decorators.py", line 62, in __call__
    return self.view_func(request, *args, **kwargs)
  File "/home/laura/tod/../tod/game/views.py", line 77, in select_prompts
    maximum_rounds = game.availablePrompts() / player_count
TypeError: unsupported operand type(s) for /: '_QuerySet' and 'int'

======================================================================
FAIL: test_tagged_item (tod.game.tests.TaggedItemTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/laura/tod/../tod/game/tests.py", line 293, in test_tagged_item
    self.failUnlessEqual(prompts.count(), 8)
AssertionError: 2 != 8

----------------------------------------------------------------------
Ran 55 tests in 5.709s

FAILED (failures=1, errors=4)
